name: "Lgputil Testing Suites"
on:
  workflow_dispatch:
jobs:
  bats-run:
    runs-on: ubuntu-latest
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Check out code
        uses: actions/checkout@v1

      - name: Set env variables
        run: |
          echo "GAME_ID=b6284467-8255-4085-849f-42459bac716f" >> $GITHUB_ENV
          echo "ORG=rakuten-games" >> $GITHUB_ENV

      - name: Install to global
        run: npm install -g .

      - name: Set auth
        run: vputil config set token ${{ secrets.VPUTIL_TOKEN }}

      - name: Set org
        run: vputil config set org $ORG

      - name: Test
        run: GAME_ID=$GAME_ID bats ./test/bats

      - name: Conditional value- status
        uses: haya14busa/action-cond@v1
        id: status
        if: always()
        with:
          cond: ${{ job.status == 'success' }}
          if_true: 'passed'
          if_false: 'failed'

      - name: Slack Notify
        uses: markkong318/slack-notification-github-action@1.0.3
        if: always()
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          CHANNEL: tests_and_deployments
          USERNAME: github
          JOB_STATUS: ${{ job.status }}
          MESSAGE: 'Vputil suites test ${{ steps.status.outputs.value }}. See details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
